version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/data  # Mount local folder to container

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    ports:
      - "3000:3000" 
      - "3001:3001"
    volumes:
      - ./config:/config
      - ./data:/data  # Mount local folder to container
    depends_on:
      - mysql

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-notebook
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work  # Mount local folder to Jupyter container
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root  # Replace with your MySQL username
      - MYSQL_PASSWORD=root  # Replace with your MySQL password
      - MYSQL_DATABASE=md_water_services  # Replace with your MySQL database name

volumes:
  mysql-data:
